In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

**Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.**

A1.

Yes, there is a difference in the data types of the variables list and array_list.

- list_: This is a Python list containing string elements.
- array_list: This is a NumPy array created from the list_. Since the list_ contains strings, the array_list will also have a data type of str.

In [7]:
list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object=list)

print(f"Data type of list_: {type(list_)}")

print(f"Data type of array_list: {array_list.dtype}")

Data type of list_: <class 'list'>
Data type of array_list: <U1


**Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.**

In [10]:
list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object=list_)

print("Data types of elements in list_:")
for item in list_:
    print(f"Element: {item}, Type: {type(item)}")

print("\nData types of elements in array_list:")
for item in array_list:
    print(f"Element: {item}, Type: {type(item)}")

Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.str_'>
Element: 2, Type: <class 'numpy.str_'>
Element: 3, Type: <class 'numpy.str_'>
Element: 4, Type: <class 'numpy.str_'>
Element: 5, Type: <class 'numpy.str_'>


**Q3. Considering the following changes in the variable, array_list:**

**array_list = np.array(object = list_, dtype = int)**

**Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.**

A3.

Yes, there will be a difference in the data types of the elements when you modify the array_list with dtype=int. When you specify dtype=int for a NumPy array, it converts all elements to integers, whereas the original list_ contains strings.

In [11]:
list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object=list_, dtype=int)

print("Data types of elements in list_:")
for item in list_:
    print(f"Element: {item}, Type: {type(item)}")

print("\nData types of elements in array_list:")
for item in array_list:
    print(f"Element: {item}, Type: {type(item)}")

Data types of elements in list_:
Element: 1, Type: <class 'str'>
Element: 2, Type: <class 'str'>
Element: 3, Type: <class 'str'>
Element: 4, Type: <class 'str'>
Element: 5, Type: <class 'str'>

Data types of elements in array_list:
Element: 1, Type: <class 'numpy.int64'>
Element: 2, Type: <class 'numpy.int64'>
Element: 3, Type: <class 'numpy.int64'>
Element: 4, Type: <class 'numpy.int64'>
Element: 5, Type: <class 'numpy.int64'>


In [12]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of the array:")
print(num_array.shape)

print("\nSize of the array:")
print(num_array.size)

Shape of the array:
(2, 3)

Size of the array:
6


**Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]**

In [15]:
zero_matrix = np.zeros((3, 3))

print("3x3 Matrix containing zeros:")
print(zero_matrix)

print("\nShape of the array:")
print(zero_matrix.shape)

print("\nSize of the array:")
print(zero_matrix.size)

3x3 Matrix containing zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Shape of the array:
(3, 3)

Size of the array:
9


**Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]**

In [16]:
identity_matrix = np.eye(5)

print("5x5 Identity Matrix:")
print(identity_matrix)

print("\nShape of the matrix:")
print(identity_matrix.shape)

print("\nSize of the matrix:")
print(identity_matrix.size)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Shape of the matrix:
(5, 5)

Size of the matrix:
25
